services:
  - type: web
    name: Sharma-Kitchen's
    runtime: python
    buildCommand: pip install -r webapp/requirements.txt
    startCommand: gunicorn --chdir webapp --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
